### ISSUE TITLE
hook 配置的问题

### ISSUE THREAD

**Issue by hsinor** [Monibuca/plugin-hook#1]
## 问题：
  一、当仅配置 urllist 时，出现 requestlist 没有初始化为 nil 的 panic。
  二、当同时配置 urllist 和 requestlist 时，出现 reflect.Value.Convert() panic
## 描述
  根据 [plugin-hook配置](https://m7s.live/guide/plugins/hook.html#%E9%85%8D%E7%BD%AE)中的描述，默认会用POST方法发送request
## Golang 版本
go 1.18.2
windows/amd64
## 期望
  能修复这两个问题
### 一、当仅配置 urllist 时，使用了未初始化内容的panic
  
![image](https://user-images.githubusercontent.com/53255091/170621001-048dd4fe-92c7-4421-b17b-7b9202cf0f04.png)

 https://github.com/Monibuca/plugin-hook/blob/d4f76fd1c415e86d8d748d089da1f534325ff8ff/main.go#L67-L71

 ### 二、同时配置 urllist 和 requestlist
 #### panic 堆栈如下
![image](https://user-images.githubusercontent.com/53255091/170621254-c28079d2-4410-4ff4-ba1d-7fdc2bfa8826.png)

#### 出问题位置
 https://github.com/Monibuca/engine/blob/d94fd98e9d34127e5d2e4df1486f119768cd1f41/config/config.go#L44-L49
![image](https://user-images.githubusercontent.com/53255091/170621797-f2bbd78a-347a-4eb2-9db4-dc689c3e7f68.png)

## 配置文件：
配置一（仅配置 urllist，不配置requestlist）
```yaml
hook:
  urllist:
    startup: "http://localhost:58888/api/monibuca/startup"
    publish: "http://localhost:58888/api/monibuca/publish"
    subscribe: "http://localhost:58888/api/monibuca/subscribe"
    streamClose: "http://localhost:58888/api/monibuca/streamClose"
```
配置二（同时配置 urllist 和 requestlist）
```yaml
hook:
  urllist:
    startup: "http://localhost:58888/api/monibuca/startup"
    publish: "http://localhost:58888/api/monibuca/publish"
    subscribe: "http://localhost:58888/api/monibuca/subscribe"
    streamClose: "http://localhost:58888/api/monibuca/streamClose"
  requestlist:
    startup:
      method: "POST"
      header:
        referer: "http://localhost:58888/api/monibuca/startup"
      url: "http://localhost:58888/api/monibuca/startup"
    publish:
      method: "POST"
      header:
        referer: "http://localhost:58888/api/monibuca/publish"
      url: "http://localhost:58888/api/monibuca/publish"
    subscribe:
      method: "POST"
      header:
        referer: "http://localhost:58888/api/monibuca/subscribe"
      url: "http://localhost:58888/api/monibuca/subscribe"
    streamClose:
      method: "POST"
      header:
        referer: "http://localhost:58888/api/monibuca/streamClose"
      url: "http://localhost:58888/api/monibuca/streamClose"
```
